name: "Lint"

on:
  push:
    branches: [master,github-actions-test, cleanup]
    paths-ignore:
    - 'README.md'
    - '.deepsource.toml'
    - '.gitignore'
    - 'setup.py'

  pull_request:
    branches: [master]
    paths-ignore:
    - 'README.md'
    - '.deepsource.toml'
    - '.gitignore'
    - 'setup.py'


jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.9]
        test-folder : ['tests']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: install dependencies [pip]
        run:  |
          pip install --upgrade pip setuptools wheel
          for req in dev-requirements.txt; do
            pip install -q -r $req
          done
          pip install -e .
      - name: linting [black and isort]
        run: |
          black . --check
          isort --profile black --check .
      - name: linting [flake8]
        run: |
          flake8 compSPI tests